"""add_player_profile_fields_transfer_fee_market_value_history

Revision ID: bc4d7bf5b515
Revises: 
Create Date: 2026-03-14 18:13:06.551488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4d7bf5b515'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_value_history',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'date', name=op.f('pk_market_value_history'))
    )
    op.create_index('ix_market_value_history_player_id', 'market_value_history', ['player_id'], unique=False)
    op.add_column('players', sa.Column('nationality_secondary', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('preferred_foot', sa.String(length=16), nullable=True))
    op.add_column('players', sa.Column('agent_name', sa.Text(), nullable=True))
    op.add_column('transfers', sa.Column('fee_paid', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'fee_paid')
    op.drop_column('players', 'agent_name')
    op.drop_column('players', 'preferred_foot')
    op.drop_column('players', 'nationality_secondary')
    op.drop_index('ix_market_value_history_player_id', table_name='market_value_history')
    op.drop_table('market_value_history')
    # ### end Alembic commands ###
